#!/usr/bin/env Rscript
# Stage 17: FI-definition sensitivity under the prespecified partial-metric
# cross-cohort measurement model. Only the free-slope structural model is fit
# for each FI definition to avoid conflating FI definition with slope equality.
suppressPackageStartupMessages({ library(haven); library(lavaan) })
ROOT <- Sys.getenv("IC_FRAILTY_STATISTICAL_MODELING", unset = "PATH_TO_STATISTICAL_MODELING")
OUT <- Sys.getenv("IC_FRAILTY_ANALYSIS_ROOT", unset = "PATH_TO_IC_FRAILTY")
CODE <- Sys.getenv("IC_FRAILTY_CODE_ROOT", unset = "PATH_TO_IC_FRAILTY_CODE")
TAB <- file.path(OUT,"tables"); dir.create(TAB,recursive=TRUE,showWarnings=FALSE)
source(file.path(CODE, "02_measurement_and_fi_validation", "29_domain_reliability_audit.R"),local=.GlobalEnv)
max_na <- function(...) { z<-cbind(...); as.numeric(apply(z,1,function(x)if(all(is.na(x)))NA_real_ else max(x,na.rm=TRUE))) }
common_frame <- function(dat,cohort) {
  if(cohort=="ELSA"){ci<-dat$imrc;cd<-dat$dlrc;ce<-dat$orient;lr<-ifelse(is.na(dat$loc_1),NA_real_,1-dat$loc_1);lm<-ifelse(is.na(dat$loc_2),NA_real_,1-dat$loc_2);gl<-max_na(dat$grip_1,dat$grip_2);gr<-max_na(dat$grip_3,dat$grip_4)}
  else if(cohort=="CHARLS"){ci<-dat$imrc;cd<-dat$dlrc;ce<-dat$orient;lr<-ifelse(is.na(dat$loc_1),NA_real_,1-dat$loc_1);lm<-ifelse(is.na(dat$loc_2),NA_real_,1-dat$loc_2);gl<-max_na(dat$grip_1,dat$grip_2);gr<-max_na(dat$grip_3,dat$grip_4)}
  else {ci<-dat$cog_imrc;cd<-dat$cog_dlrc;ce<-pmin(dat$cog_ser7,4);lr<-ifelse(is.na(dat$loc_1),NA_real_,1-as.numeric(dat$loc_1>0));lm<-ifelse(is.na(dat$loc_2),NA_real_,1-as.numeric(dat$loc_2>0));gl<-dat$grip_1;gr<-dat$grip_2}
  pb<-function(x){x<-as.numeric(x);if(cohort=="CHARLS")ifelse(is.na(x),NA_real_,as.numeric(x>=3))else ifelse(is.na(x),NA_real_,as.numeric(x>=1))}
  data.frame(cog_imrc=as.numeric(ci)/10,cog_dlrc=as.numeric(cd)/10,cog_exec=as.numeric(ce)/4,loc_room=as.numeric(lr),loc_100m=as.numeric(lm),grip_left=as.numeric(gl)/100,grip_right=as.numeric(gr)/100,psych_dep=pb(dat$psych_1),psych_effort=pb(dat$psych_2),psych_sleep=pb(dat$psych_3),psych_happy=pb(dat$psych_4),fi_primary=100*as.numeric(dat$fi_primary),fi_complete8=100*as.numeric(dat$fi_complete8),fi_without_srh=100*as.numeric(dat$fi_without_srh),cohort=cohort)
}
harm<-do.call(rbind,list(common_frame(elsa,"ELSA"),common_frame(charls,"CHARLS"),common_frame(hrs,"HRS")));harm$cohort<-factor(harm$cohort,levels=c("ELSA","CHARLS","HRS"));ordered_items<-c("loc_room","loc_100m","psych_dep","psych_effort","psych_sleep","psych_happy");for(v in ordered_items)harm[[v]]<-as.ordered(harm[[v]])
partial_loadings<-c("cognition=~cog_exec","grip_vitality=~grip_right","locomotion=~loc_100m","psychological=~psych_happy")
make_syntax<-function(outcome)paste("cognition =~ cog_imrc + cog_dlrc + cog_exec","locomotion =~ loc_room + loc_100m","grip_vitality =~ grip_left + grip_right","psychological =~ psych_dep + psych_effort + psych_sleep + psych_happy",paste0(outcome," ~ cognition + locomotion + grip_vitality + psychological"),"cognition ~~ locomotion + grip_vitality + psychological","locomotion ~~ grip_vitality + psychological","grip_vitality ~~ psychological",sep="\n")
fit_one<-function(outcome){f<-tryCatch(sem(make_syntax(outcome),data=harm,group="cohort",ordered=ordered_items,estimator="WLSMV",parameterization="theta",std.lv=TRUE,meanstructure=TRUE,missing="pairwise",group.equal="loadings",group.partial=partial_loadings),error=function(e)structure(list(error=conditionMessage(e)),class="fit_error")); if(inherits(f,"fit_error"))return(list(fit=f,fitrow=data.frame(outcome=outcome,converged=FALSE,post_check=FALSE,n=NA,chisq=NA,df=NA,cfi=NA,tli=NA,rmsea=NA,srmr=NA,error=f$error),coef=NULL)); conv<-lavInspect(f,"converged");fm<-if(conv)fitMeasures(f,c("chisq","df","cfi","tli","rmsea","srmr"))else setNames(rep(NA_real_,6),c("chisq","df","cfi","tli","rmsea","srmr"));pe<-parameterEstimates(f,standardized=TRUE);z<-pe[pe$op=="~"&pe$lhs==outcome,c("lhs","rhs","group","est","se","pvalue","std.all")];z$outcome<-outcome;z$capacity_oriented_est<-ifelse(z$rhs=="psychological",-z$est,z$est);z$capacity_oriented_std_all<-ifelse(z$rhs=="psychological",-z$std.all,z$std.all);list(fit=f,fitrow=data.frame(outcome=outcome,converged=conv,post_check=tryCatch(lavInspect(f,"post.check"),error=function(e)NA),n=sum(lavInspect(f,"nobs")),t(as.data.frame(fm)),error=NA_character_,check.names=FALSE),coef=z)}
outs<-c("fi_primary","fi_complete8","fi_without_srh");res<-lapply(outs,fit_one);fit_tab<-do.call(rbind,lapply(res,`[[`,"fitrow"));coef_tab<-do.call(rbind,lapply(res,`[[`,"coef"));write.csv(fit_tab,file.path(TAB,"stage17_cross_cohort_fi_sensitivity_fit.csv"),row.names=FALSE,fileEncoding="UTF-8");write.csv(coef_tab,file.path(TAB,"stage17_cross_cohort_fi_sensitivity_coefficients.csv"),row.names=FALSE,fileEncoding="UTF-8")
writeLines(c("# Stage 17 cross-cohort FI-definition sensitivity","","Each FI definition is fit under the same prespecified partial-metric loading model with cohort-specific structural slopes. FI is expressed in percentage points for numerical scaling; coefficient signs use the harmonized direction (higher locomotion/cognition/grip = better capacity; psychological = higher-worse before the capacity-oriented sign reversal).","","The primary definition uses six chronic diseases, self-rated health and BMI clinical threshold with at least 6/8 observed components and the observed denominator. Complete-8 and omit-self-rated-health variants are sensitivity definitions. These models are exploratory structural association checks and do not compare latent means.","","Outputs: tables/stage17_cross_cohort_fi_sensitivity_fit.csv and tables/stage17_cross_cohort_fi_sensitivity_coefficients.csv."),file.path(OUT,"stage17_cross_cohort_fi_sensitivity_memo.md"))
writeLines(c(paste0("timestamp=",format(Sys.time(),tz="UTC")),paste0("R=",R.version.string),paste0("lavaan=",as.character(packageVersion("lavaan"))),"design=partial metric free-slope FI-definition sensitivity"),file.path(OUT,"stage17_cross_cohort_fi_sensitivity_run_info.txt"));cat("Wrote Stage 17 FI sensitivity outputs.\n")
